Update PublishNuGet.yml

diff --git a/.github/workflows/PublishNuGet.yml b/.github/workflows/PublishNuGet.yml
--- a/.github/workflows/PublishNuGet.yml
+++ b/.github/workflows/PublishNuGet.yml
@@ -64,14 +64,14 @@ jobs:
           -p:PackageReleaseNotes="$RELEASE_NOTES" \
           -o ./nupkgs
 
-      #- name: Push to NuGet
-       # run: |
-        #  for pkg in ./nupkgs/*.nupkg; do
-         #   echo "Pushing $pkg to NuGet..."
-          #  if dotnet nuget push "$pkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}; then
-           #   echo "Successfully pushed $pkg."
-            #else
-             # echo "ERROR: Failed to push $pkg." >&2
-              #exit 1
-            #fi
-          #done
+      - name: Push to NuGet
+        run: |
+          for pkg in ./nupkgs/*.nupkg; do
+            echo "Pushing $pkg to NuGet..."
+            if dotnet nuget push "$pkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}; then
+              echo "Successfully pushed $pkg."
+            else
+              echo "ERROR: Failed to push $pkg." >&2
+              exit 1
+            fi
+          done
